### ISSUE TITLE
Ajout d'un script de CI

### ISSUE THREAD

**Issue by Lecrapouille** [baudaux/exa-kernel#1]
La demo sur ta page web semble vieille, car `echo toto | wc` ne marche pas. Ajoute un fichier de CI du genre https://github.com/Lecrapouille/zipper/blob/master/.github/workflows/ci.yaml (oublie celui de windows). Tu peux mettre plusieurs fichiers yaml. Déjà un pour compiler, ensuite, on verra comment deployer sur ta page web.

**Comment by baudaux** [comment]
Salut Quentin,

J’y connais rien en CI faudrait que tu m’expliques. Le code du noyau est compilé en web assembly alors je vois pas comment tu veux faire exécuter ca sur le serveur

A+,
Benoit

**Comment by Lecrapouille** [comment]
done
