### ISSUE TITLE
exaequos don't support multitab on firefox

### ISSUE THREAD

**Issue by xcombelle** [baudaux/exa-kernel#3]
Step to reproduce:

1. go to https://exaequos.com/ with firefox
2. click on start:  in the center of the window  a tab is opened in the foreground
3.  go back to the first tab
4. click on start: a black screen happen (eventually whole firefox is frozen

If it is useful, I use firefox with ublock origin

**Comment by baudaux** [comment]
Hi Xavier, it is a current limitation of EXA kernel. Processes use W3C broadcast Channel API. So different tabs interfer. When a new tab is added, kernel needs to check if there is already a running instance. Drivers need to ne instantiated only once

**Comment by baudaux** [comment]
I have upgraded exaequOS for supporting multi tabs/windows, with no impact on the kernel

**Comment by baudaux** [comment]
I have upgraded exaequOS for supporting multi tabs/windows, with no impact on the kernel. There is one unique instance of the kernel
